name: Deploy .NET Core App to Somee via FTP

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Bajar el c√≥digo
    - uses: actions/checkout@v4

    # 2. Instalar .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 3. Compilar
    - name: Publish
      run: dotnet publish -c Release -o ./publish

    # 4. Crear el archivo app_offline.htm
    - name: Create app_offline.htm
      run: |
        echo "<html><body><h1>Actualizando Sitio... Espere un momento.</h1></body></html>" > app_offline.htm

    # 5. FASE 1: APAGAR EL SITIO (Entrar a la carpeta -> Subir app_offline.htm)
    - name: Stop App (Upload app_offline.htm)
      run: |
        sudo apt-get update
        sudo apt-get install lftp
        lftp -e "set ssl:verify-certificate no; cd /www.TeamFinderApiv2.somee.com/; put app_offline.htm; bye" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}

    # 6. Esperar a que se liberen los archivos
    - name: Wait for Lock Release
      run: sleep 10

    # 7. FASE 2: DESPLEGAR (Ignorando app_offline para no borrarlo)
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/
        server-dir: /www.TeamFinderApiv2.somee.com/
        exclude: |
          **/.git*
          **/.git*/**
          **/app_offline.htm

    # 8. FASE 3: ARRANCAR EL SITIO (Entrar a la carpeta -> Borrar app_offline.htm)
    - name: Start App (Remove app_offline.htm)
      if: always()
      run: |
        lftp -e "set ssl:verify-certificate no; cd /www.TeamFinderApiv2.somee.com/; rm app_offline.htm; bye" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}
